CREATE TABLE tehtava (
	t_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	t_kuvaus TEXT NOT NULL,
	t_lisatiedot TEXT,
	t_status INT NOT NULL DEFAULT '0',
	t_deadlinedtm DATETIME DEFAULT NULL,
	t_ryhma VARCHAR(255) DEFAULT NULL,
	t_jaettu tinyint(4) NOT NULL DEFAULT '0',
	t_tekija varchar(50) NOT NULL,
) ENGINE=InnoDB AUTO_INCREMENT=59 DEFAULT CHARSET=utf8;

CREATE TABLE kayttaja (
	k_nimi VARCHAR(100) NOT NULL, 
	k_salasana VARCHAR(100) NOT NULL, 
	k_rooli VARCHAR (50) NOT NULL, 
	PRIMARY KEY (k_nimi)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE kayttajan_tehtava (
	kt_id INT(11) NOT NULL AUTO_INCREMENT, 
	kt_t_id INT(11) NOT NULL, 
	kt_k_nimi VARCHAR(100) NOT NULL, 
	PRIMARY KEY (kt_id), 
	CONSTRAINT kt_k_nimi FOREIGN KEY (kt_k_nimi) REFERENCES kayttaja (k_nimi) 
	ON DELETE CASCADE 
	ON UPDATE CASCADE,
	CONSTRAINT kt_t_id FOREIGN KEY (kt_t_id) REFERENCES tehtava (t_id) 
	ON DELETE CASCADE 
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;
