CREATE TABLE tehtava (
	t_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	t_kuvaus VARCHAR(255) NOT NULL,
	t_lisatiedot VARCHAR(255),
	t_status INT NOT NULL DEFAULT '0',
	t_deadlinedtm DATETIME,
	t_ryhma VARCHAR(255), 
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
