CREATE TABLE Task (
	t_id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	t_task VARCHAR(1000) NOT NULL,
	t_expire DATETIME DEFAULT NULL,
	t_group VARCHAR(50) DEFAULT NULL,
	t_shared TINYINT(4) NOT NULL DEFAULT 0,
	t_user VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE User (
	u_user VARCHAR(100) NOT NULL, 
	u_password VARCHAR(100) NOT NULL, 
	u_role VARCHAR(50) NOT NULL, 
	u_enabled TINYINT(4) NOT NULL DEFAULT 1,
	PRIMARY KEY (u_user)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE Usertask (
	ut_task INT(11) NOT NULL, 
	ut_user VARCHAR(100) NOT NULL,
	ut_done TINYINT(4) NOT NULL DEFAULT 0, 
	PRIMARY KEY (ut_task, ut_user), 
	CONSTRAINT ut_user FOREIGN KEY (ut_user) REFERENCES User(u_user) 
	ON DELETE CASCADE 
	ON UPDATE CASCADE,
	CONSTRAINT ut_task FOREIGN KEY (ut_task) REFERENCES Task(t_id) 
	ON DELETE CASCADE
	ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
	
CREATE TABLE Comment (
	c_id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	c_comment VARCHAR(500) NOT NULL,
	c_datetime DATETIME NOT NULL,
	c_task INT(11) NOT NULL,
	c_user VARCHAR(100) NOT NULL,
	CONSTRAINT c_task FOREIGN KEY (c_task) REFERENCES Task(t_id)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	CONSTRAINT c_user FOREIGN KEY (c_user) REFERENCES User(u_user)
	ON DELETE CASCADE
	ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
